#!/usr/bin/env python3
"""Generate source/core/ancient_dialogues.inc from the decompiled C# and the game's loc (X6).

For every Ancient with an AncientDialogueSet (AncientEventModel.DefineDialogues): the first-visit-ever
dialogue, the per-character dialogues (VisitIndex), the character-agnostic ones and the
AnyCharacterDialogueBlacklist. AncientDialogue.PopulateLines is resolved here against the zhs
`ancients` table: each line's key ends in ".ancient" when that key exists, else ".char"; a dialogue
whose first line has the "r" suffix is repeating. The result is committed like characters.inc;
rerun after a decompiler or game update:  python3 tools/gen_ancient_dialogues.py [--pck PATH]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from gdpck import Game  # noqa: E402

ROOT = os.path.dirname(HERE)
DEC = os.path.join(os.path.dirname(ROOT), 'sts2-decompiled', 'MegaCrit.Sts2.Core.Models.Events')
ANCIENTS = ['Neow', 'Orobas', 'Pael', 'Tezcatara', 'Nonupeipe', 'Tanx', 'Vakuu', 'Darv']
OUT = os.path.join(ROOT, 'source', 'core', 'ancient_dialogues.inc')

DIALOGUE = re.compile(r'new AncientDialogue\(((?:"[^"]*"(?:, )?)*)\)(\s*\{\s*VisitIndex = (\d+)\s*\})?')


def upper_snake(name):
    return re.sub(r'(?<=[a-z])(?=[A-Z])', '_', name).upper()


def dialogues(text):
    """[(line count, visit index or None)] in source order."""
    out = []
    for m in DIALOGUE.finditer(text):
        n = len(re.findall(r'"[^"]*"', m.group(1)))
        out.append((n, int(m.group(3)) if m.group(3) else None))
    return out


def lines(loc, anc, who, index, count):
    """AncientDialogue.PopulateLines: (repeating, [line keys])."""
    def exists(k):
        return k in loc
    base = f'{anc}.talk.{who}.{index}-0'
    rep = exists(base + 'r.ancient') or exists(base + 'r.char')
    keys = []
    for i in range(count):
        k = f'{anc}.talk.{who}.{index}-{i}' + ('r' if rep else '')
        keys.append(k + '.ancient' if exists(k + '.ancient') else k + '.char')
    return rep, keys


def cpp_dialogue(rep, keys, visit):
    ks = ', '.join(f'"{k}"' for k in keys)
    return f'{{{-1 if visit is None else visit}, {"true" if rep else "false"}, {{{ks}}}}}'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--pck', help='path to "Slay the Spire 2.pck" (default: Steam install)')
    args = ap.parse_args()
    loc = Game(args.pck).loc('zhs', 'ancients')
    out = ['// Generated by tools/gen_ancient_dialogues.py from the decompiled C#',
           '// (AncientEventModel.DefineDialogues) and the zhs ancients table. Do not edit.',
           'static std::vector<AncientDialogueSet> makeAncientDialogues() {',
           '  std::vector<AncientDialogueSet> v;']
    for name in ANCIENTS:
        text = open(os.path.join(DEC, name + '.cs'), encoding='utf-8').read()
        body = text[text.index('DefineDialogues()'):]
        body = body[:body.index('return ancientDialogueSet;')]
        anc = upper_snake(name)
        out.append('  {')
        out.append('    AncientDialogueSet s;')
        out.append(f'    s.ancient = "{name}";')
        m = re.search(r'FirstVisitEverDialogue = (null|new AncientDialogue\([^)]*\))', body)
        if m and m.group(1) != 'null':
            n = len(re.findall(r'"[^"]*"', m.group(1)))
            rep, keys = lines(loc, anc, 'firstVisitEver', 0, n)
            out.append(f'    s.firstVisitEver = {cpp_dialogue(rep, keys, None)};')
            out.append('    s.hasFirstVisitEver = true;')
        chars = body[body.index('CharacterDialogues'):body.index('AgnosticDialogues')]
        marks = list(re.finditer(r'CharKey<(\w+)>\(\)\]', chars))
        for j, cm in enumerate(marks):
            key = cm.group(1).upper()
            block = chars[cm.end():marks[j + 1].start() if j + 1 < len(marks) else len(chars)]
            ds = [cpp_dialogue(*lines(loc, anc, key, i, n), visit) for i, (n, visit) in enumerate(dialogues(block))]
            out.append(f'    s.characters["{key}"] = {{{", ".join(ds)}}};')
        agn = body[body.index('AgnosticDialogues'):]
        ds = [cpp_dialogue(*lines(loc, anc, 'ANY', i, n), visit) for i, (n, visit) in enumerate(dialogues(agn))]
        out.append(f'    s.agnostic = {{{", ".join(ds)}}};')
        bl = re.search(r'AnyCharacterDialogueBlacklist => (.*?);\n', text)
        if bl:
            for c in re.findall(r'Character<(\w+)>', bl.group(1)):
                out.append(f'    s.anyBlacklist.push_back("{c}");')
        out.append('    v.push_back(std::move(s));')
        out.append('  }')
    out += ['  return v;', '}', '']
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    print('wrote', OUT)


if __name__ == '__main__':
    main()
