#!/usr/bin/env python3
"""Generates source/ui/sfx_tables.inc from the decompiled C# (SfxCmd / WithHitFx / WithAttackerFx literals,
MonsterModel.TakeDamageSfxType, DeathSfx/HurtSfx overrides). Run when the decompiled tree changes.
Output is names only: card/monster class id -> sound event or one-shot file name."""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..', '..', 'sts2-decompiled')
CARDS = os.path.join(ROOT, 'MegaCrit.Sts2.Core.Models.Cards')
MONS = os.path.join(ROOT, 'MegaCrit.Sts2.Core.Models.Monsters')
LIT = re.compile(r'"((?:event:/sfx/[^"]+)|(?:[a-z_]+\.mp3))"')


def calls(src, name):
    return [LIT.findall(m.group(1)) for m in re.finditer(name + r'\(([^;]*)', src)]


def first(lst):
    for l in lst:
        if l:
            return l[0]
    return None


def snake(n):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', n).lower()


def plays(src):
    seen = []
    for m in re.finditer(r'SfxCmd\.Play\(\s*"([^"]+)"', src):
        if m.group(1) not in seen:
            seen.append(m.group(1))
    for m in re.finditer(r'const string _\w*Sfx = "([^"]+)"', src):
        if m.group(1) not in seen:
            seen.append(m.group(1))
    return seen


def read(d, f):
    return open(os.path.join(d, f), encoding='utf-8', errors='ignore').read()


rows = {k: [] for k in ('CARD_HIT', 'CARD_PLAY', 'MON_ATTACK', 'MON_HIT', 'MON_CAST', 'MON_DMG', 'MON_DEATH',
                        'MON_HURT', 'MON_MOVE')}


def move_sounds(n, s):
    """MON_MOVE: "Class/MOVE_ID" -> the first SfxCmd.Play literal in that move's method (new MoveState("ID", Method, ...))."""
    out = []
    for mid, meth in re.findall(r'new MoveState\(\s*"([A-Z0-9_]+)"\s*,\s*(\w+)', s):
        m = re.search(r'(?:async\s+)?Task\s+' + meth + r'\s*\([^)]*\)\s*\{', s)
        if not m:
            continue
        nxt = re.search(r'\n\t(?:public|private|protected|internal)\s', s[m.end():])
        body = s[m.end():m.end() + (nxt.start() if nxt else len(s))]
        lit = re.search(r'SfxCmd\.Play\(\s*"([^"]+)"', body)
        if lit:
            out.append((n + '/' + mid, lit.group(1)))
    return out
for f in sorted(os.listdir(CARDS)):
    if not f.endswith('.cs'):
        continue
    n, s = f[:-3], read(CARDS, f)
    h = first(calls(s, 'WithHitFx'))
    if h:
        rows['CARD_HIT'].append((n, h))
    p = plays(s)
    if not p:
        a = first(calls(s, 'WithAttackerFx'))
        p = [a] if a else []
    if p:
        rows['CARD_PLAY'].append((n, p[0]))
for f in sorted(os.listdir(MONS)):
    if not f.endswith('.cs'):
        continue
    n, s = f[:-3], read(MONS, f)
    for key, val in (('MON_ATTACK', first(calls(s, 'WithAttackerFx'))), ('MON_HIT', first(calls(s, 'WithHitFx'))),
                     ('MON_CAST', (plays(s) or [None])[0])):
        if val:
            rows[key].append((n, val))
    rows['MON_MOVE'].extend(move_sounds(n, s))
    m = re.search(r'TakeDamageSfxType => DamageSfxType\.(\w+)', s)
    if m:
        rows['MON_DMG'].append((n, snake(m.group(1))))
    m = re.search(r'string DeathSfx => "([^"]+)"', s)
    if m:
        rows['MON_DEATH'].append((n, m.group(1)))
    if 'HasDeathSfx => false' in s:
        rows['MON_DEATH'].append((n, ''))
    m = re.search(r'string\??\s+HurtSfx => "([^"]+)"', s)
    if m:
        rows['MON_HURT'].append((n, m.group(1)))
out = os.path.join(HERE, '..', 'source', 'ui', 'sfx_tables.inc')
with open(out, 'w', newline='\n') as o:
    o.write('// Generated by tools/gen_sfx_tables.py - do not edit. class id -> sound name.\n')
    for k, v in rows.items():
        o.write('static const SfxRow %s[] = {\n' % k)
        for a, b in v:
            o.write('  {"%s", "%s"},\n' % (a, b))
        o.write('  {nullptr, nullptr}};\n')
print({k: len(v) for k, v in rows.items()})
