#!/usr/bin/env python3
"""Generate source/ui/pinyin_table.inc: pinyin collation ranks for the CJK characters in card titles.

The deck view's 拼音顺序 sort (NDeckViewScreen, zh-CN culture) orders titles by pinyin. This writes
one {code point, rank} row per CJK character used in `cards.*.title` of loc.txt; rank orders the
syllables (letters, then tone), characters with the same syllable tie and fall back to code point.
Needs `pypinyin` (pip install --user pypinyin); only the generated table is committed.
Usage: python3 tools/gen_pinyin.py [path/to/loc.txt]
"""
import os
import re
import sys

from pypinyin import Style, pinyin

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
loc = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'romfs', 'loc.txt')
chars = set()
with open(loc, encoding='utf-8') as f:
    for line in f:
        k, _, v = line.rstrip('\n').partition('\t')
        if re.fullmatch(r'cards\.[A-Z0-9_]+\.title', k):
            chars.update(c for c in v if '㐀' <= c <= '鿿')
syl = {}
for c in chars:
    s = pinyin(c, style=Style.TONE3, heteronym=False, neutral_tone_with_five=True)[0][0]
    m = re.fullmatch(r'([^0-9]+)([1-5]?)', s)
    syl[c] = (m.group(1), int(m.group(2) or 5)) if m else (s, 5)
order = sorted(set(syl.values()))
rank = {s: i + 1 for i, s in enumerate(order)}
rows = sorted((ord(c), rank[syl[c]]) for c in chars)
with open(os.path.join(ROOT, 'source', 'ui', 'pinyin_table.inc'), 'w', newline='\n') as f:
    f.write('// Generated by tools/gen_pinyin.py (pypinyin) -- do not edit. {code point, pinyin rank}, sorted.\n')
    for i in range(0, len(rows), 6):
        f.write(''.join('{0x%x,%d},' % r for r in rows[i:i + 6]) + '\n')
print(len(rows), 'chars,', len(order), 'syllables')
