#!/usr/bin/env python3
"""Generate source/core/characters.inc from the decompiled C# (../sts2-decompiled).

One `Character` per playable character: HP, gold, energy, orb slots, starter deck, starting
relic, card / relic / potion pools in the C# order, and the multiplayer-only cards that
CardFactory.FilterForPlayerCount drops in single player. Run it again after the decompiler
output changes; the result is committed like the other translated tables.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEC = os.path.join(os.path.dirname(ROOT), 'sts2-decompiled')
CHARS = ['Ironclad', 'Silent', 'Defect', 'Regent', 'Necrobinder']


def read(*parts):
    with open(os.path.join(DEC, *parts), encoding='utf-8') as f:
        return f.read()


def ids(text, kind):
    return re.findall(r'ModelDb\.' + kind + r'<(\w+)>', text)


def cpp_list(items, indent='      '):
    lines, cur = [], indent
    for it in items:
        tok = '"%s", ' % it
        if len(cur) + len(tok) > 118:
            lines.append(cur.rstrip())
            cur = indent
        cur += tok
    lines.append(cur.rstrip().rstrip(','))
    return '\n'.join(lines)


def main():
    mp_only = {}
    cards_dir = os.path.join(DEC, 'MegaCrit.Sts2.Core.Models.Cards')
    mp_cards = set()
    for fn in os.listdir(cards_dir):
        if 'CardMultiplayerConstraint.MultiplayerOnly' in read('MegaCrit.Sts2.Core.Models.Cards', fn):
            mp_cards.add(fn[:-3])
    out = ['// Generated by tools/gen_characters.py from Models.Characters, the card / relic pools and the',
           '// <Character>4Epoch potion lists. Do not edit by hand; rerun the script.',
           '', 'namespace sts {', 'namespace {', '',
           'std::vector<Character> makeCharacters() {', '  std::vector<Character> v;']
    for c in CHARS:
        t = read('MegaCrit.Sts2.Core.Models.Characters', c + '.cs')
        hp = int(re.search(r'StartingHp => (\d+)', t).group(1))
        gold = int(re.search(r'StartingGold => (\d+)', t).group(1))
        m = re.search(r'MaxEnergy => (\d+)', t)
        energy = int(m.group(1)) if m else 3
        m = re.search(r'BaseOrbSlotCount => (\d+)', t)
        orbs = int(m.group(1)) if m else 0
        stars = 'ShouldAlwaysShowStarCounter => true' in t
        deck = ids(t.split('StartingDeck')[1].split('StartingRelics')[0], 'Card')
        relics = ids(t.split('StartingRelics')[1], 'Relic')
        pool = read('MegaCrit.Sts2.Core.Models.CardPools', c + 'CardPool.cs')
        cards = ids(pool, 'Card')
        color = re.search(r'EnergyColorName => "(\w+)"', pool).group(1)
        frame = re.search(r'CardFrameMaterialPath => "(\w+)"', pool).group(1)
        relic_pool = ids(read('MegaCrit.Sts2.Core.Models.RelicPools', c + 'RelicPool.cs'), 'Relic')
        potions = re.findall(r'Potion<(\w+)>', read('MegaCrit.Sts2.Core.Timeline.Epochs', c + '4Epoch.cs'))
        mp = [x for x in cards if x in mp_cards]
        out += ['  {', '    Character c;',
                '    c.id = "%s"; c.key = "%s";' % (c, c.upper()),
                '    c.startingHp = %d; c.startingGold = %d; c.maxEnergy = %d; c.orbSlots = %d; c.alwaysShowStars = %s;'
                % (hp, gold, energy, orbs, 'true' if stars else 'false'),
                '    c.energyColor = "%s"; c.cardFrame = "%s";' % (color, frame),
                '    c.starterDeck = {%s};' % ', '.join('"%s"' % x for x in deck),
                '    c.startingRelics = {%s};' % ', '.join('"%s"' % x for x in relics),
                '    c.potions = {%s};' % ', '.join('"%s"' % x for x in potions),
                '    c.relicPool = {%s};' % ', '.join('"%s"' % x for x in relic_pool),
                '    c.multiplayerOnly = {%s};' % ', '.join('"%s"' % x for x in mp),
                '    c.cardPool = {', cpp_list(cards), '    };',
                '    v.push_back(std::move(c));', '  }']
    out += ['  return v;', '}', '', '}  // namespace', '}  // namespace sts', '']
    with open(os.path.join(ROOT, 'source', 'core', 'characters.inc'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    print('wrote characters.inc')


if __name__ == '__main__':
    sys.exit(main())
