#!/usr/bin/env python3
"""Generate source/ui/hover_tips.inc from the decompiled C# (../sts2-decompiled).

S20: the detail popup lists a model's hover tips next to it (C# CardModel / RelicModel /
PotionModel / EnchantmentModel .ExtraHoverTips). Each entry is "<kind>:<ClassName>" -> a
';'-separated list of tips in the C# order:
  P:<POWER_KEY>   HoverTipFactory.FromPower<T> (powers.<KEY>.title / description)
  S:<STATIC_KEY>  HoverTipFactory.Static(StaticHoverTip.X) and the energy tip (static_hover_tips)
  K:<KEYWORD>     HoverTipFactory.FromKeyword (card_keywords)
  C:<CardClass>   HoverTipFactory.FromCard<T> (the card's name and text)
  E:<ENCH_KEY>    HoverTipFactory.FromEnchantment<T> (enchantments)
  O:<POTION_KEY>  HoverTipFactory.FromPotion<T> (potions)
  R:<ORB_KEY>     HoverTipFactory.FromOrb<T> (orbs; shown once that loc table exists)
Tips whose loc is missing at run time are skipped, so unported powers cost nothing. The
result is committed like the other translated tables; rerun after the decompile changes.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEC = os.path.join(os.path.dirname(ROOT), 'sts2-decompiled')
DIRS = [('card', 'MegaCrit.Sts2.Core.Models.Cards'), ('relic', 'MegaCrit.Sts2.Core.Models.Relics'),
        ('potion', 'MegaCrit.Sts2.Core.Models.Potions'), ('ench', 'MegaCrit.Sts2.Core.Models.Enchantments')]


def slug(name):  # StringHelper.Slugify: VulnerablePower -> VULNERABLE_POWER
    s = re.sub(r'(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])', '_', name)
    return s.upper()


TOKENS = [
    (r'HoverTipFactory\.FromPower(?:WithPowerHoverTips)?<(\w+)>', lambda m: ['P:' + slug(m)]),
    (r'HoverTipFactory\.Static\(StaticHoverTip\.(\w+)', lambda m: ['S:' + slug(m)]),
    (r'HoverTipFactory\.FromKeyword\(CardKeyword\.(\w+)\)', lambda m: ['K:' + slug(m)]),
    (r'HoverTipFactory\.FromCard(?:WithCardHoverTips)?<(\w+)>', lambda m: ['C:' + m]),
    (r'HoverTipFactory\.FromEnchantment<(\w+)>', lambda m: ['E:' + slug(m)]),
    (r'HoverTipFactory\.FromPotion<(\w+)>', lambda m: ['O:' + slug(m)]),
    (r'HoverTipFactory\.FromOrb<(\w+)>', lambda m: ['R:' + slug(m)]),
    (r'(EnergyHoverTip|HoverTipFactory\.ForEnergy)', lambda m: ['S:ENERGY']),
    (r'HoverTipFactory\.(FromForge)\(\)', lambda m: ['S:FORGE', 'C:SovereignBlade']),
]
PATTERN = re.compile('|'.join('(?:%s)' % t for t, _ in TOKENS))


def body(text):
    """The ExtraHoverTips property's source (expression or getter block), or ''."""
    m = re.search(r'IEnumerable<IHoverTip> ExtraHoverTips\b', text)
    if not m:
        return ''
    i = m.end()
    rest = text[i:]
    if rest.lstrip().startswith('=>'):
        depth = 0
        for j, ch in enumerate(rest):
            if ch in '({[':
                depth += 1
            elif ch in ')}]':
                depth -= 1
            elif ch == ';' and depth == 0:
                return rest[:j]
        return rest
    start = rest.find('{')
    depth = 0
    for j in range(start, len(rest)):
        if rest[j] == '{':
            depth += 1
        elif rest[j] == '}':
            depth -= 1
            if depth == 0:
                return rest[start:j]
    return ''


def tips(src):
    out = []
    for m in PATTERN.finditer(src):
        for k, (tok, fn) in enumerate(TOKENS):
            g = m.group(k + 1)
            if g is not None:
                for t in fn(g):
                    if t not in out:
                        out.append(t)
                break
    return out


def main():
    rows = []
    for kind, d in DIRS:
        path = os.path.join(DEC, d)
        for fn in sorted(os.listdir(path)):
            if not fn.endswith('.cs'):
                continue
            with open(os.path.join(path, fn), encoding='utf-8') as f:
                t = tips(body(f.read()))
            if t:
                rows.append('{"%s:%s", "%s"},' % (kind, fn[:-3], ';'.join(t)))
    out = os.path.join(ROOT, 'source', 'ui', 'hover_tips.inc')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Generated by tools/gen_hover_tips.py from the C# ExtraHoverTips (S20). Do not edit.\n')
        f.write('\n'.join(rows) + '\n')
    print(f'{len(rows)} entries -> {out}')


if __name__ == '__main__':
    main()
