#!/usr/bin/env python3
"""Generate source/core/monster_pacing.inc from the decompiled C# monsters (ANIM_DIFF C11 / M2).

Per monster class: the first attack-animation delay of its attacks (AttackCommand.WithAttackerAnim(name,
delay); FromMonster without it: 0) and the wait of its moves without an attack: the first
TriggerAnim(base.Creature, "Cast", wait), or, for a class without one, its first TriggerAnim(base.Creature,
"Attack", wait) (a non-damage move playing the attack anim: EyeWithTeeth, TrackerRubyRaider's Track, ...). Our translated moves don't carry these waits, so combat.cpp applies them per monster.
Usage: python3 tools/gen_monster_pacing.py [path/to/sts2-decompiled]
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def find_decomp():
    d = ROOT  # ../sts2-decompiled next to the repo (also from a worktree inside it)
    while d != os.path.dirname(d):
        d = os.path.dirname(d)
        if os.path.isdir(os.path.join(d, 'sts2-decompiled')):
            return os.path.join(d, 'sts2-decompiled')
    sys.exit('sts2-decompiled not found; pass its path')


DECOMP = sys.argv[1] if len(sys.argv) > 1 else find_decomp()
SRC = os.path.join(DECOMP, 'MegaCrit.Sts2.Core.Models.Monsters')
OUT = os.path.join(ROOT, 'source', 'core', 'monster_pacing.inc')

# Hand-checked exceptions (see combat.cpp monsterPacing):
OVERRIDES = {
    # 0 s attack anim after a Cmd.Wait(0.4); its Charge (not "Cast") after a Cmd.Wait(0.75).
    'CubexConstruct': (0.4, 0.75),
}
NO_CAST = {'TheInsatiable', 'LagavulinMatriarch', 'Fogmog'}  # ported moves already wait for their anims

ATTACK = re.compile(r'WithAttackerAnim\(\s*"[^"]*"\s*,\s*([0-9.]+)f?')
CAST = re.compile(r'TriggerAnim\(base\.Creature,\s*"Cast",\s*([0-9.]+)f?\)')
ANIM_ATTACK = re.compile(r'TriggerAnim\(base\.Creature,\s*"Attack",\s*([0-9.]+)f?\)')


def fmt(v):
    s = repr(float(v))
    return (s[:-1] if s.endswith('.0') else s) + 'f'


BASE = re.compile(r'class\s+\w+\s*:\s*(\w+)')
texts = {n[:-3]: open(os.path.join(SRC, n), encoding='utf-8').read() for n in os.listdir(SRC) if n.endswith('.cs')}


def first(mid, *pats):
    """First match in the class, else in its base class (MysteriousKnight : FlailKnight)."""
    while mid in texts:
        for pat in pats:
            m = pat.search(texts[mid])
            if m:
                return float(m.group(1))
        b = BASE.search(texts[mid])
        mid = b.group(1) if b else None
    return 0.0


rows = []
for mid in texts:
    atk = first(mid, ATTACK)
    cast = first(mid, CAST, ANIM_ATTACK) if mid not in NO_CAST else 0.0
    atk, cast = OVERRIDES.get(mid, (atk, cast))
    if atk or cast:
        rows.append((mid, atk, cast))

rows.sort(key=lambda r: r[0].encode())  # byte order: the table is searched with std::lower_bound
with open(OUT, 'w', newline='\n') as f:
    f.write('// Generated by tools/gen_monster_pacing.py from the decompiled C# monsters; do not edit.\n')
    f.write('// {id, attack anim delay, cast wait} (normal speed), sorted by id.\n')
    for mid, atk, cast in rows:
        f.write(f'    {{"{mid}", {fmt(atk)}, {fmt(cast)}}},\n')
print(f'{len(rows)} monsters -> {OUT}')
