#!/usr/bin/env python3
"""Generate source/ui/pinyin_table.inc: pinyin collation ranks for all GB2312 hanzi.

The deck view's 拼音顺序 sort (NDeckViewScreen, zh-CN culture) orders titles by pinyin. This writes
one {code point, rank} row per GB2312 level-1 + level-2 hanzi (bytes 0xB0A1-0xF7FE, ~6.7k); rank
orders the syllables (letters, then tone), characters with the same syllable tie and fall back to
code point. Independent of the game's data. Needs `pypinyin` (pip install --user pypinyin).
Usage: python3 tools/gen_pinyin.py
"""
import os
import re

from pypinyin import Style, pinyin

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
chars = set()
for hi in range(0xB0, 0xF8):
    for lo in range(0xA1, 0xFF):
        try:
            c = bytes([hi, lo]).decode('gb2312')
        except UnicodeDecodeError:
            continue
        if '一' <= c <= '鿿':
            chars.add(c)
syl = {}
for c in chars:
    s = pinyin(c, style=Style.TONE3, heteronym=False, neutral_tone_with_five=True)[0][0]
    m = re.fullmatch(r'([^0-9]+)([1-5]?)', s)
    syl[c] = (m.group(1), int(m.group(2) or 5)) if m else (s, 5)
order = sorted(set(syl.values()))
rank = {s: i + 1 for i, s in enumerate(order)}
rows = sorted((ord(c), rank[syl[c]]) for c in chars)
with open(os.path.join(ROOT, 'source', 'ui', 'pinyin_table.inc'), 'w', newline='\n') as f:
    f.write('// Generated by tools/gen_pinyin.py (pypinyin) -- do not edit. {code point, pinyin rank}, sorted.\n')
    for i in range(0, len(rows), 8):
        f.write(''.join('{0x%x,%d},' % r for r in rows[i:i + 8]) + '\n')
print(len(rows), 'chars,', len(order), 'syllables')
